### ISSUE TITLE
lib iconv

### ISSUE THREAD

**Issue by lisik** [CBMM/tagging#4]
Running into the error: 

ld: library not found for -liconv

I'm on OSX 10.11.4

**Comment by imalsogreg** [comment]
The problem is in `uuid` funnily enough. `uuid` depends on some c libs, `unix`, `process`, which were failing in the ghcjs environment. Switching to `uuid-types` solves the problem. Will clean up the solution and post tomorrow.

**Comment by imalsogreg** [comment]
closed by 88d0cad86ed2f3b50a5610b2f219dde4bfc2c734
